main:
  bin: "__package_path__\\bin\\rdiff-backup.exe"
  ssh: "__package_path__\\bin\\ssh.exe"
backups:
  - name: "example"
    source: "C:\\Windows\\Temp"
    dest: "user@backupfriend::/backup/media/usb/example"
    port: "8022"
    key: "__user_data__\\id_rsa"
    server_username: admin
    server_url: http://backupfriend
    every: "daily"
    time: "08:00"
