name: Build python package

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-on-testpypi:
    name: 📦 Publish on TestPyPI
    if: github.event_name == 'release'
    needs:
      - pre-commit
      - test-unit
      - test-install
      - test-e2e
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Download build result
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: 📦 Publish to index
        uses: pypa/gh-action-pypi-publish@master
        continue-on-error: true
        with:
          user: __token__
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/

  publish-on-pypi:
    name: 📦 Publish tagged releases to PyPI
    if: github.event_name == 'release'
    needs: publish-on-testpypi
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Download build result
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - name: 📦 Publish to index
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
